### PR TITLE
printing city details for the match selected by user

### PR DESCRIPTION
**Pull request by camelPhonso**
relates #14

added printCityDetails to render info on the match selected and also added printHTML to let us render elements more easily. I'm finding it helps on some situations but it's not the best for others. Have a look at what you think

### CODE REVIEW

**Review by carlthedev — DISMISSED** [review]
Good stuff, but im nervous about the merge conflicts it has thrown. I also need to add try catch to police fetch for error handling.

**Comment by camelPhonso** [comment]
> Good stuff, but im nervous about the merge conflicts it has thrown. I also need to add try catch to police fetch for error handling.

Yep, I was expecting some conflicts because these changes touch on so many parts of the page. But I think if we go through each line we'll see that a lot of those changes are simple spaces or class name changes

**Comment by camelPhonso** [comment]
resolved the conflicts 👍 should be good to merge

**Review by carlthedev — APPROVED** [review]
fantastic, will merge now

**Pull request merged**
