### PR TITLE
tweak search behaviour

### PR DESCRIPTION
**Pull request by camelPhonso**
added behaviour feedback for the user when searching a city and tweaked the look of the page in accordance with the feedback from the last code review

### CODE REVIEW

**Review by carlthedev — CHANGES_REQUESTED** [review]
Ive had a good look at this, its a rabbit hole. i would say just go for a normal if statement.

**Comment by camelPhonso** [comment]
> Ive had a good look at this, its a rabbit hole. i would say just go for a normal if statement.

yep, fair enough. I had a look and turned it into an if statement right here, please have a look. The issue was an extra logic step we needed on the check I think, it's working this way

**Review by carlthedev — APPROVED** [review]
Looks good.

**Review by carlthedev — APPROVED** [review]
Looks good.

**Review by carlthedev — DISMISSED** [review]
Awsome

**Review by carlthedev — APPROVED** [review]
Conflicts resolved now, good to merge.

**Pull request merged**
